languages:  
  JavaScript: true
exclude_paths:
  - node_modules/**/*
  - src/vendor/**/*
  - src/gulpfile.js
  - src/package.json
  - src/tsconfig.json
  - src/tslint.json
  - "LICENSE"
  - "README.md"
