engines:
  tslint:
    enabled: true
    config: tslint.json
ratings:
  paths:
    - "**.ts"
exclude_paths:
- node_modules/**/*
- typings/**/*
- "README.md"
- "LICENSE"
- "src/gulpfile.js"
- "src/package.json"
- "src/tsconfig.json"
- "src/tslint.json"
- "src/assets/*"