language: node_js
sudo: false
node_js:
  - "6.9.1" 
install:
  - cd src && npm install
after_script:
  - npm install -g codeclimate-test-reporter
  - npm test
  - npm run coverage > codeclimate-test-reporter 