language: node_js
sudo: false
node_js:
  - "6.9.1" 
install:
  - cd src && npm install
before_script:
  - npm install -g gulp  
script: gulp
after_script:
  - npm install -g codeclimate-test-reporter
  - gulp test
  - codeclimate-test-reporter < dist/unit-test-coverage/lcov.info